baseURL = "/"
languageCode = "en-us"
title = "abijango"
theme = "hugo-journal"

[params]
  twitter_username = "abijango"
  Author = "Naufal Mir"
  githubUsername = "abijango"
  twitterUsername = "abijango"
  tagline = "Writing random crap since 2013"

[permalinks]
  post = "/:year/:month/:day/:title/"