baseURL = "https://abijango.github.io"
languageCode = "en-us"
title = "Abijango"
enableRobotsTXT = true
# site config

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  description = "Random nonsense of one guy."
  githubUsername = "abijango"
  twitterUsername = "abijango"
  tagline = "Random crap since 2013."

[module]
  [[module.imports]]
    path = 'github.com/abijango/hugo-journal'
    # project theme