baseURL = ""
languageCode = "en-us"
title = "Butterfly Dream"
theme = "pixyll"

[params]
  twitter_username = "abijango"
  paginate = true
  author = "Naufal Mir"

[permalinks]
  post = "/:year/:month/:day/:title/"

  # number of posts to show on index
  # default: 10
  # HomepagePosts = 5
